apiVersion: v2
name: aws-smtp-relay
description: A Helm chart for AWS SMTP Relay (SES/Pinpoint) with EKS Pod Identity support
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - smtp
  - aws
  - ses
  - pinpoint
  - relay
  - eks
home: https://github.com/KamorionLabs/aws-smtp-relay
sources:
  - https://github.com/KamorionLabs/aws-smtp-relay
maintainers:
  - name: Kamorion Labs
