{{- if or .Values.config.password .Values.config.bcryptHash .Values.config.tls.keyPassphrase }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-smtp-relay.fullname" . }}
  labels:
    {{- include "aws-smtp-relay.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.password }}
  password: {{ .Values.config.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.bcryptHash }}
  bcrypt-hash: {{ .Values.config.bcryptHash | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.tls.keyPassphrase }}
  tls-key-passphrase: {{ .Values.config.tls.keyPassphrase | b64enc | quote }}
  {{- end }}
{{- end }}
